apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: mariadb-namespace
  labels:
    app: mariadb
  annotations:
    description: Service for MariaDB database server
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: mariadb
